-   id: stylelint
    name: stylelint
    entry: stylelint
    language: node
    files: \.(css|scss|sass|less)$

    # Use additional_dependencies to install the actual node package
    minimum_pre_commit_version: 2.0.0
