-   id: stylelint
    name: stylelint
    entry: stylelint
    language: node
    files: \.(css|scss|sass|less)$
    minimum_pre_commit_version: 2.0.0
    additional_dependencies:
        - stylelint@13.7.2
        - prettier@2.1.2
        - stylelint-prettier@1.1.2
        - stylelint-config-prettier@8.0.2
